trigger:
- main

variables:
    BuildConfiguration: Release
    DotNetVersion: 6.0.x

stages:

- stage: BuildiOS
  jobs:
  - job: BuildMAUIApps
    displayName: Build OneDrake App
    pool:
      vmImage: 'macOS-12'
      demands:
      - MSBuild
      
    steps:
    
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-apple-ios-macos-tvos-or-watchos-app
    # Setup Secret Pipeline Variable or Library Secrets Variable for iOS Certificate Password
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'OneDrakeAppDist.p12'
        certPwd: '$(iOSCertPassword)'
        keychain: 'temp'

    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'OneDrakeAppProvProfile.mobileprovision'

    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '$(DotNetVersion)'
    
    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    
    - task: Bash@3
      displayName: Restore nuget
      inputs:
        targetType: 'inline'
        script: |
          cd 6.0/Apps/DrakeAzureDevopsMobile/src/
          dotnet restore DrakeAzureDevopsMobile.sln
    - task: ios-bundle-version@1
      inputs:
        sourcePath: '/Users/runner/work/1/s/DrakeAzureDevopsMobile/Platforms/iOS/Info.plist'
        versionCodeOption: 'buildid'
        versionCode: '1.1.$(Build.BuildId)'
        versionName: '1.1.$(Build.BuildId)'
        printFile: true
  # https://docs.microsoft.com/en-us/dotnet/maui/ios/deployment/overview
    - task: Bash@3
      displayName: Build iOS App
      inputs:
        targetType: 'inline'
        script: |
          cd 6.0/Apps/DrakeAzureDevopsMobile/src
          dotnet publish -f net6.0-ios -c Release /p:RuntimeIdentifiers=ios-arm64 

    - task: CopyFiles@2
      inputs:
        Contents: |
          **/*.app
          **/*.ipa
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop_ios'
        publishLocation: 'Container'

    - task: AppStoreRelease@1
      inputs:
        serviceEndpoint: 'iOSDevAppStore'
        releaseTrack: 'TestFlight'
        appIdentifier: 'com.drakeintl.onedrakeapp'
        appType: 'iOS'
        appSpecificId: '1661927729'
        shouldSkipWaitingForProcessing: true
