trigger:
- main

variables:
    BuildConfiguration: Release
    DotNetVersion: 6.0.300
    VSVERSION: 17/pre

stages:
- stage: BuildAndroid
  jobs:
  - job: BuildMAUIApps
    displayName: Build OneDrake App
    pool:
      vmImage: 'windows-2022'
      demands:
      - MSBuild
      
    steps:
    
    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '$(DotNetVersion)'
    
    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    
    - task: Bash@3
      displayName: Restore nuget
      inputs:
        targetType: 'inline'
        script: |
          cd "6.0/Apps/Drake Azure Devops Mobile/src/"
          dotnet restore DrakeAzureDevopsMobile.sln
    - task: android-manifest-version@1
      inputs:
        sourcePath: D:\a\1\s\DrakeAzureDevopsMobile\Platforms\Android\AndroidManifest.xml
        versionCodeOption: 'buildid'
        versionCode: '$(Build.BuildId)'
        versionName: '1.0.$(Build.BuildId)'
        printFile: true

  # https://docs.microsoft.com/en-us/dotnet/maui/android/deployment/overview
    - task: Bash@3
      displayName: Build Android App
      inputs:
        targetType: 'inline'
        script: |
          cd "6.0/Apps/Drake Azure Devops Mobile/src"
          dotnet build -f net6.0-android -c Release

    # Signing Android App : https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/mobile/app-signing?view=azure-devops&tabs=apple-install-during-build#sign-your-android-app

    - task: CopyFiles@2
      inputs:
        Contents: |
          **\**\DrakeAzureDevopsMobile\bin\Release\net6.0-android\*.apk
          D:\a\1\s\DrakeAzureDevopsMobile\bin\Release\net6.0-android\*.apk
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop_android'
        publishLocation: 'Container'

    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'OneDrakeApp-Android'
        appSlug: 'MRafer-ph.drakeintl.com/OneDrakeApp-Android'
        appFile: 'D:\a\1\s\DrakeAzureDevopsMobile\bin\Release\net6.0-android\com.drakeintl.onedrakeapp-Signed.apk'
        buildVersion: '2.0'
        symbolsOption: 'Android'
        releaseNotesOption: 'input'
        releaseNotesInput: 'For testing'
        destinationType: 'groups'
  